class GeneralInfo
  def self.kids_id
    @@kids_id = {"Tarjeta de identidad" => "TI", "Registro civil" => "RC", "NUIP" => "NUIP" , "Otro" => "Otro"}
  end
	
	def self.adult_id
		@@adult_id = {"Cedula de Ciudadania" => "CC", "Cedula de extranjeria" => "CE" , "Otro" => "Otro"}
	end
	
	def self.gender
		@@gender = ["femenino", "masculino"]
	end
	
	def self.estrato
		@@estrato = {"Estrato 1" => "1", "Estrato 2" => "2", "Estrato 3" => "3" , "Estrato 4" => "4"}
	end
	
	def self.period
		@@period = ["", "I periodo", "II periodo","III periodo","IV periodo", "V periodo"]
	end
	
	def self.lines
		@@lines = {"Educación publica de calidad" => "epc", "Herramientas para la vida" => "h", "Nutrición" => "n"} 
	end
	
	def self.departments
		@@departments = ["Amazonas", "Antioquia", "Arauca", "Atlantico", "Bogotá D.C", "Bolívar", "Boyaca", "Caldas", "Caqueta", "Casanare", "Cauca", "Cesar", "Cordoba", "Cundinamarca", "Choco", "Guainia", "Guaviare", "Huila", "La Guajira", "Magdalena", "Meta", "Narino", "Norte de Santander", "Putumayo", "Quindio", "Risaralda", "San Andres", "Santander", "Sucre", "Tolima", "Valle", "Vaupes", "Vichada"]
	end
	
	def self.nutrition_points
		@@nutrition_points = {
			"femenino" => {"lower" => 11.8, "minimum" => 13.25, "medium_min" => 13.83, "medium_max" => 16.9, "maximum" => 18.9},
			"masculino" => {"lower" => 12.1, "minimum" => 13, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}
		}
	end
	
	def self.nutrition_points_five
    
    @@nutrition_points_five = Hash.new({
				"femenino" => {"lower" => 14.7, "minimum" => 16.4, "medium_min" => 18.6, "medium_max" => 24.8, "maximum" => 29.5},
				"masculino" => {"lower" => 15.7, "minimum" => 17.3, "medium_min" => 19.2, "medium_max" => 24.9, "maximum" => 29.2}	
		})

    @@nutrition_points_five[0.0] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 18.9},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}	
    }

    @@nutrition_points_five[0.5] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 18.9},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}	
    }
    
    @@nutrition_points_five[1.0] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 18.9},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}	
    }

    @@nutrition_points_five[1.5] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 18.9},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}	
    }

    @@nutrition_points_five[2.0] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 18.9},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}	
    }

    @@nutrition_points_five[2.5] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 18.9},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}	
    }

    @@nutrition_points_five[3.0] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 18.9},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}	
    }

    @@nutrition_points_five[3.5] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 18.9},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}	
    }

    @@nutrition_points_five[4.0] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 18.9},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}	
    }

    @@nutrition_points_five[4.5] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 18.9},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}	
    }

    @@nutrition_points_five[5.0] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 18.9},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.6, "maximum" => 18.3}	
    }

    @@nutrition_points_five[5.5] = {
      "femenino" => {"lower" => 11.7, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 16.9, "maximum" => 19.0},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.7, "maximum" => 18.4}	
    }

    @@nutrition_points_five[6.0] = {
      "femenino" => {"lower" => 11.7, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 17.0, "maximum" => 19.2},
      "masculino" => {"lower" => 12.1, "minimum" => 13.0, "medium_min" => 14.1, "medium_max" => 16.8, "maximum" => 18.5}	
    }

    @@nutrition_points_five[6.5] = {
      "femenino" => {"lower" => 11.7, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 17.1, "maximum" => 19.5},
      "masculino" => {"lower" => 12.2, "minimum" => 13.1, "medium_min" => 14.1, "medium_max" => 16.9, "maximum" => 18.7}	
    }

    @@nutrition_points_five[7.0] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.7, "medium_min" => 13.9, "medium_max" => 17.3, "maximum" => 19.8},
      "masculino" => {"lower" => 12.3, "minimum" => 13.1, "medium_min" => 14.2, "medium_max" => 17.0, "maximum" => 19.0}	
    }

    @@nutrition_points_five[7.5] = {
      "femenino" => {"lower" => 11.8, "minimum" => 12.8, "medium_min" => 14.0, "medium_max" => 17.5, "maximum" => 20.1},
      "masculino" => {"lower" => 12.3, "minimum" => 13.2, "medium_min" => 14.3, "medium_max" => 17.2, "maximum" => 19.3}	
    }

    @@nutrition_points_five[8.0] = {
      "femenino" => {"lower" => 11.9, "minimum" => 12.9, "medium_min" => 14.1, "medium_max" => 17.7, "maximum" => 20.6},
      "masculino" => {"lower" => 12.4, "minimum" => 13.3, "medium_min" => 14.4, "medium_max" => 17.4, "maximum" => 19.7}	
    }

    @@nutrition_points_five[8.5] = {
      "femenino" => {"lower" => 12.0, "minimum" => 13.0, "medium_min" => 14.3, "medium_max" => 18.0, "maximum" => 21.0},
      "masculino" => {"lower" => 12.5, "minimum" => 13.4, "medium_min" => 14.5, "medium_max" => 17.7, "maximum" => 20.1}	
    }

    @@nutrition_points_five[9.0] = {
      "femenino" => {"lower" => 12.1, "minimum" => 13.1, "medium_min" => 14.4, "medium_max" => 18.3, "maximum" => 21.5},
      "masculino" => {"lower" => 12.6, "minimum" => 13.5, "medium_min" => 14.6, "medium_max" => 17.9, "maximum" => 20.5}	
    }

    @@nutrition_points_five[9.5] = {
      "femenino" => {"lower" => 12.2, "minimum" => 13.3, "medium_min" => 14.6, "medium_max" => 18.7, "maximum" => 22.0},
      "masculino" => {"lower" => 12.7, "minimum" => 13.6, "medium_min" => 14.8, "medium_max" => 18.2, "maximum" => 20.9}	
    }

    @@nutrition_points_five[10.0] = {
      "femenino" => {"lower" => 12.4, "minimum" => 13.5, "medium_min" => 14.8, "medium_max" => 19.0, "maximum" => 22.6},
      "masculino" => {"lower" => 12.8, "minimum" => 13.7, "medium_min" => 14.9, "medium_max" => 18.5, "maximum" => 21.4}	
    }

    @@nutrition_points_five[10.5] = {
      "femenino" => {"lower" => 12.5, "minimum" => 13.7, "medium_min" => 15.1, "medium_max" => 19.4, "maximum" => 23.1},
      "masculino" => {"lower" => 12.9, "minimum" => 13.9, "medium_min" => 15.1, "medium_max" => 18.8, "maximum" => 21.9}	
    }

    @@nutrition_points_five[11.0] = {
      "femenino" => {"lower" => 12.7, "minimum" => 13.9, "medium_min" => 15.3, "medium_max" => 19.9, "maximum" => 23.7},
      "masculino" => {"lower" => 13.1, "minimum" => 14.1, "medium_min" => 15.3, "medium_max" => 19.2, "maximum" => 22.5}	
    }

    @@nutrition_points_five[11.5] = {
      "femenino" => {"lower" => 12.9, "minimum" => 14.1, "medium_min" => 15.6, "medium_max" => 20.3, "maximum" => 24.3},
      "masculino" => {"lower" => 13.2, "minimum" => 14.2, "medium_min" => 15.5, "medium_max" => 19.5, "maximum" => 23.0}	
    }

    @@nutrition_points_five[12.0] = {
      "femenino" => {"lower" => 13.2, "minimum" => 14.4, "medium_min" => 16.0, "medium_max" => 20.8, "maximum" => 25.0},
      "masculino" => {"lower" => 13.4, "minimum" => 14.5, "medium_min" => 15.8, "medium_max" => 19.9, "maximum" => 23.6}	
    }

    @@nutrition_points_five[12.5] = {
      "femenino" => {"lower" => 13.4, "minimum" => 14.7, "medium_min" => 16.3, "medium_max" => 21.3, "maximum" => 25.6},
      "masculino" => {"lower" => 13.6, "minimum" => 14.7, "medium_min" => 16.1, "medium_max" => 20.4, "maximum" => 24.2}	
    }

    @@nutrition_points_five[13.0] = {
      "femenino" => {"lower" => 13.6, "minimum" => 14.9, "medium_min" => 16.6, "medium_max" => 21.8, "maximum" => 26.2},
      "masculino" => {"lower" => 13.8, "minimum" => 14.9, "medium_min" => 16.4, "medium_max" => 20.8, "maximum" => 24.8}	
    }

    @@nutrition_points_five[13.5] = {
      "femenino" => {"lower" => 13.8, "minimum" => 15.2, "medium_min" => 16.9, "medium_max" => 22.3, "maximum" => 26.8},
      "masculino" => {"lower" => 14.0, "minimum" => 15.2, "medium_min" => 16.7, "medium_max" => 21.3, "maximum" => 25.3}	
    }

    @@nutrition_points_five[14.0] = {
      "femenino" => {"lower" => 14.0, "minimum" => 15.4, "medium_min" => 17.2, "medium_max" => 22.7, "maximum" => 27.3},
      "masculino" => {"lower" => 14.3, "minimum" => 15.5, "medium_min" => 17.0, "medium_max" => 21.8, "maximum" => 25.9}	
    }

    @@nutrition_points_five[14.5] = {
      "femenino" => {"lower" => 14.2, "minimum" => 15.7, "medium_min" => 17.5, "medium_max" => 23.1, "maximum" => 27.8},
      "masculino" => {"lower" => 14.5, "minimum" => 15.7, "medium_min" => 17.3, "medium_max" => 22.2, "maximum" => 26.5}	
    }

    @@nutrition_points_five[15.0] = {
      "femenino" => {"lower" => 14.4, "minimum" => 15.9, "medium_min" => 17.8, "medium_max" => 23.5, "maximum" => 28.2},
      "masculino" => {"lower" => 14.7, "minimum" => 16.0, "medium_min" => 17.6, "medium_max" => 22.7, "maximum" => 27.0}	
    }

    @@nutrition_points_five[15.5] = {
      "femenino" => {"lower" => 14.5, "minimum" => 16.0, "medium_min" => 18.0, "medium_max" => 23.8, "maximum" => 28.6},
      "masculino" => {"lower" => 14.9, "minimum" => 16.3, "medium_min" => 18.0, "medium_max" => 23.1, "maximum" => 27.4}	
    }

    @@nutrition_points_five[16.0] = {
      "femenino" => {"lower" => 14.6, "minimum" => 16.2, "medium_min" => 18.2, "medium_max" => 24.1, "maximum" => 28.9},
      "masculino" => {"lower" => 15.1, "minimum" => 16.5, "medium_min" => 18.2, "medium_max" => 23.5, "maximum" => 27.9}	
    }

    @@nutrition_points_five[16.5] = {
      "femenino" => {"lower" => 14.7, "minimum" => 16.3, "medium_min" => 18.3, "medium_max" => 24.3, "maximum" => 29.1},
      "masculino" => {"lower" => 15.3, "minimum" => 16.7, "medium_min" => 18.5, "medium_max" => 23.9, "maximum" => 28.3}	
    }

    @@nutrition_points_five[17.0] = {
      "femenino" => {"lower" => 14.7, "minimum" => 16.4, "medium_min" => 18.4, "medium_max" => 24.5, "maximum" => 29.3},
      "masculino" => {"lower" => 15.4, "minimum" => 16.9, "medium_min" => 18.8, "medium_max" => 24.3, "maximum" => 28.6}	
    }

    @@nutrition_points_five[17.5] = {
      "femenino" => {"lower" => 14.7, "minimum" => 16.4, "medium_min" => 18.5, "medium_max" => 24.6, "maximum" => 29.4},
      "masculino" => {"lower" => 15.6, "minimum" => 17.1, "medium_min" => 19.0, "medium_max" => 24.6, "maximum" => 29.0}	
    }

    @@nutrition_points_five[18.0] = {
      "femenino" => {"lower" => 14.7, "minimum" => 16.4, "medium_min" => 18.6, "medium_max" => 24.8, "maximum" => 29.5},
      "masculino" => {"lower" => 15.7, "minimum" => 17.3, "medium_min" => 19.2, "medium_max" => 24.9, "maximum" => 29.2}	
    }

    @@nutrition_points_five
	end
	
	def self.cities
    @@cities = {
    	:"Amazonas" => [
    		"Leticia",
    		"Puerto Narino"
    	],
    	:"Antioquia" => [
    		"Abejorral",
    		"Abriaqui",
    		"Alejandria",
    		"Amaga",
    		"Amalfi",
    		"Andes",
    		"Angelopolis",
    		"Angostura",
    		"Anori",
    		"Antioquia",
    		"Anza",
    		"Apartado",
    		"Arboletes",
    		"Argelia",
    		"Armenia",
    		"Barbosa",
    		"Belmira",
    		"Bello",
    		"Betania",
    		"Betulia",
    		"Bolivar",
    		"Briseno",
    		"Buritica",
    		"Caceres",
    		"Caicedo",
    		"Caldas",
    		"Campamento",
    		"Canasgordas",
    		"Caracoli",
    		"Caramanta",
    		"Carepa",
    		"Carmen de Viboral",
    		"Carolina",
    		"Caucasia",
    		"Chigorodo",
    		"Cisneros",
    		"Cocorna",
    		"Concepcion",
    		"Concordia",
    		"Copacabana",
    		"Dabeiba",
    		"Don Matias",
    		"Ebejico",
    		"El Bagre",
    		"Entrerrios",
    		"Envigado",
    		"Fredonia",
    		"Frontino",
    		"Giraldo",
    		"Girardota",
    		"Gomez Plata",
    		"Granada",
    		"Guadalupe",
    		"Guarne",
    		"Guatape",
    		"Heliconia",
    		"Hispania",
    		"Itagui",
    		"Ituango",
    		"Jardin",
    		"Jerico",
    		"La Ceja",
    		"La Estrella",
    		"La Pintada",
    		"La Union",
    		"Liborina",
    		"Maceo",
    		"Marinilla",
    		"Medellin",
    		"Montebello",
    		"Murindo",
    		"Mutata",
    		"Narino",
    		"Necocli",
    		"Nechi",
    		"Olaya",
    		"Penol",
    		"Peque",
    		"Pueblorrico",
    		"Puerto Berrio",
    		"Puerto Nare",
    		"Puerto Triunfo",
    		"Remedios",
    		"Retiro",
    		"Rionegro",
    		"Sabanalarga",
    		"Sabaneta",
    		"Salgar",
    		"San Andres",
    		"San Carlos",
    		"San francisco",
    		"San Jeronimo",
    		"San Jose de Montana",
    		"San Juan de Uraba",
    		"San Luis",
    		"San Pedro",
    		"San Pedro de Uraba",
    		"San Rafael",
    		"San Roque",
    		"San Vicente",
    		"Santa Barbara",
    		"Santa Rosa de Osos",
    		"Santo Domingo",
    		"Santuario",
    		"Segovia",
    		"Sonson",
    		"Sopetran",
    		"Tamesis",
    		"Taraza",
    		"Tarso",
    		"Titiribi",
    		"Toledo",
    		"Turbo",
    		"Uramita",
    		"Urrao",
    		"Valdivia",
    		"Valparaiso",
    		"Vegachi",
    		"Venecia",
    		"Vigia del Fuerte",
    		"Yali",
    		"Yarumal",
    		"Yolombo",
    		"Yondo (Casabe)",
    		"Zaragoza"
    	],
    	:"Arauca" => [
    		"Arauca",
    		"Arauquita",
    		"Cravo Norte",
    		"Fortul",
    		"Saravena",
    		"Tame"
    	],
    	:"Atlantico" => [
    		"Barranquilla",
    		"Baranoa",
    		"Campo de la Cruz",
    		"Candelaria",
    		"Galapa",
    		"Juan de Acosta",
    		"Luruaco",
    		"Malambo",
    		"Manati",
    		"Palmar de Varela",
    		"Piojo",
    		"Polonuevo",
    		"Ponedera",
    		"Puerto Colombia",
    		"Repelon",
    		"Sabanagrande",
    		"Sabanalarga",
    		"Santa Lucia",
    		"Santo Tomas",
    		"Soledad",
    		"Suan",
    		"Tubara",
    		"Usiacuri"
    	],
    	:"Bogotá D.C" => [
    		"Bogota D.C"
    	],
      :"Bolívar" => [
    		"Cartagena de Indias",
    		"Achi",
    		"Altos del Rosario",
    		"Arenal",
    		"Arjona",
    		"Arroyohondo",
    		"Barranco de Loba",
    		"Calamar",
    		"Cantagallo",
    		"Cicuco",
    		"Clemencia",
    		"Cordoba",
    		"El Carmen de Bolivar",
    		"El Guamo",
    		"El Penon",
    		"Hatillo de Loba",
    		"Magangue",
    		"Mahates",
    		"Margarita",
    		"Maria la Baja",
    		"Montecristo",
    		"Mompos",
    		"Morales",
    		"Pinillos",
    		"Regidor",
    		"Rio Viejo",
    		"San Cristobal",
    		"San Estanislao",
    		"San Fernando",
    		"San Jacinto",
    		"San Jacinto del Cauca",
    		"San Juan Nepomuceno",
    		"San Martin de Loba",
    		"San Pablo",
    		"Santa Catalina",
    		"Santa Rosa",
    		"Santa Rosa del Sur",
    		"Simiti",
    		"Soplaviento",
    		"Talaigua Nuevo",
    		"Tiquisio (Puerto Rico)",
    		"Turbaco",
    		"Turbana",
    		"Villanueva",
    		"Zambrano"
      ],
    	:"Boyaca" => [
    		"Almeida",
    		"Aquitania",
    		"Arcabuco",
    		"Belen",
    		"Berbeo",
    		"Beteitiva",
    		"Boavita",
    		"Boyaca",
    		"Briseno",
    		"Buenavista",
    		"Busbanza",
    		"Caldas",
    		"Campohermoso",
    		"Cerinza",
    		"Chinavita",
    		"Chiquinquira",
    		"Chiscas",
    		"Chita",
    		"Chitaranque",
    		"Chivata",
    		"Cienaga",
    		"Combita",
    		"Coper",
    		"Corrales",
    		"Covarachia",
    		"Cubar",
    		"Cucaita",
    		"Cuitiva",
    		"Chiquiza",
    		"Chivor",
    		"Duitama",
    		"El Cocuy",
    		"El Espino",
    		"Firavitoba",
    		"Floresta",
    		"Gachantiva",
    		"Gameza",
    		"Garagoa",
    		"Guacamayas",
    		"Guateque",
    		"Guayata",
    		"Guican",
    		"Iza",
    		"Jenesano",
    		"Jerico",
    		"Labranzagrande",
    		"La Capilla",
    		"La Victoria",
    		"La Ubita",
    		"Villa de Leyva",
    		"Macanal",
    		"Maripi",
    		"Miraflores",
    		"Mongua",
    		"Mongui",
    		"Moniquira",
    		"Motavita",
    		"Muzo",
    		"Nobsa",
    		"Nuevo Colon",
    		"Oicata",
    		"Otanche",
    		"Pachavita",
    		"Paez",
    		"Paipa",
    		"Pajarito",
    		"Panqueba",
    		"Pauna",
    		"Paya",
    		"Paz de Rio",
    		"Pesca",
    		"Pisva",
    		"Puerto Boyaca",
    		"Quipama",
    		"Ramiquiri",
    		"Raquira",
    		"Rondon",
    		"Saboya",
    		"Sachica",
    		"Samaca",
    		"San Eduardo",
    		"San Jose de Pare",
    		"San Luis de Gaceno",
    		"San Mateo",
    		"San Miguel de Sema",
    		"San Pablo de Borbur",
    		"Santana",
    		"Santa Maria",
    		"Santa Rosa de Viterbo",
    		"Santa Sofia",
    		"Sativanorte",
    		"Sativasur",
    		"Siachoque",
    		"Soata",
    		"Socota",
    		"Socha",
    		"Sogamoso",
    		"Somondoco",
    		"Sora",
    		"Sotaquira",
    		"Soraca",
    		"Susacon",
    		"Sutamarchan",
    		"Sutatenza",
    		"Tasco",
    		"Tenza",
    		"Tibana",
    		"Tibasosa",
    		"Tinjaca",
    		"Tipacoque",
    		"Toca",
    		"Togui",
    		"Topaga",
    		"Tota",
    		"Tunja",
    		"Tunungua",
    		"Turmeque",
    		"Tuta",
    		"Tutaza",
    		"Umbita",
    		"Ventaquemada",
    		"Viracacha",
    		"Zetaquira"
    	],
    	:"Caldas" => [
    		"Aguadas",
    		"Anserma",
    		"Aranzazu",
    		"Belalcazar",
    		"Chinchina",
    		"Filadelfia",
    		"La Dorada",
    		"La Merced",
    		"Manizales",
    		"Manzanares",
    		"Marmato",
    		"Marquetalia",
    		"Marulanda",
    		"Neira",
    		"Pacora",
    		"Palestina",
    		"Pensilvania",
    		"Riosucio",
    		"Risaralda",
    		"Salamina",
    		"Samana",
    		"San Jose",
    		"Supia",
    		"Victoria",
    		"Villamaria",
    		"Viterbo"
    	],
    	:"Caqueta" => [
    		"Albania",
    		"Belen de los Andaquies",
    		"Cartagena del Chaira",
    		"Curillo",
    		"El Doncello",
    		"El Paujil",
    		"Florencia",
    		"La Montanita",
    		"Milan",
    		"Morelia",
    		"Puerto Rico",
    		"San Jose del Fragua",
    		"San Vicente del Caguan",
    		"Solano",
    		"Solita",
    		"Valparaiso"
    	],
    	:"Casanare" => [
    		"Aguazul",
    		"Chameza",
    		"Hato Corozal",
    		"La Salina",
    		"Mani",
    		"Monterrey",
    		"Nunchia",
    		"Orocue",
    		"Paz de Ariporo",
    		"Pore",
    		"Recetor",
    		"Sabalarga",
    		"Sacama",
    		"San Luis de Palenque",
    		"Tamara",
    		"Tauramena",
    		"Trinidad",
    		"Villanueva",
    		"Yopal"
    	],
    	:"Cauca" => [
    		"Almaguer",
    		"Argelia",
    		"Balboa",
    		"Bolivar",
    		"Buenos Aires",
    		"Cajibio",
    		"Caldono",
    		"Caloto",
    		"Corinto",
    		"El Tambo",
    		"Florencia",
    		"Guapi",
    		"Inza",
    		"Jambalo",
    		"La Sierra",
    		"La Vega",
    		"Lopez (Micay)",
    		"Mercaderes",
    		"Miranda",
    		"Morales",
    		"Padilla",
    		"Paez (Belalcazar)",
    		"Patia (El Bordo)",
    		"Piamonte",
    		"Piendamo",
    		"Popayan",
    		"Puerto Tejada",
    		"Purace (Coconuco)",
    		"Rosas",
    		"San Sebastian",
    		"Santander de Quilichao",
    		"Santa Rosa",
    		"Silvia",
    		"Sotara (Paispamba)",
    		"Suarez",
    		"Timbio",
    		"Timbiqui",
    		"Toribio",
    		"Totoro"
    	],
    	:"Cesar" => [
    		"Aguachica",
    		"Agustin Codazzi",
    		"Astrea",
    		"Becerril",
    		"Bosconia",
    		"Chimichagua",
    		"Chiriguana",
    		"Curumani",
    		"El Copey",
    		"El Paso",
    		"Gamarra",
    		"Gonzalez",
    		"La Gloria",
    		"La Jagua de Ibirico",
    		"Manaure Balcon Cesar",
    		"Pailitas",
    		"Pelaya",
    		"Pueblo Bello",
    		"Rio de Oro",
    		"La Paz (Robles)",
    		"San Alberto",
    		"San Diego",
    		"San Martin",
    		"Tamalameque",
    		"Valledupar"
    	],
    	:"Cordoba" => [
    		"Ayapel",
    		"Buenavista",
    		"Canalete",
    		"Cerete",
    		"Chima",
    		"Chinu",
    		"Cienaga de Oro",
    		"Cotorra",
    		"La Apartada (Frontera)",
    		"Lorica",
    		"Los Cordobas",
    		"Momil",
    		"Monitos",
    		"Montelibano",
    		"Monteria",
    		"Planeta Rica",
    		"Pueblo Nuevo",
    		"Puerto Escondido",
    		"Puerto Libertador",
    		"Purisima",
    		"Sahagun",
    		"San Andres Sotavento",
    		"San Antero",
    		"San Bernardo del Viento",
    		"San Carlos",
    		"San Pelayo",
    		"Tierralta",
    		"Valencia"
    	],
    	:"Cundinamarca" => [
    		"Agua de Dios",
    		"Alban",
    		"Anapoima",
    		"Anolaima",
    		"Arbelaez",
    		"Beltran",
    		"Bituima",
    		"Bojaca",
    		"Cabrera",
    		"Cachipay",
    		"Cajica",
    		"Caparrapi",
    		"Caqueza",
    		"Carmen de Carupa",
    		"Chaguani",
    		"Chia",
    		"Chipaque",
    		"Choachi",
    		"Choconta",
    		"Cogua",
    		"Cota",
    		"Cucunuba",
    		"El Colegio",
    		"El Penon",
    		"El Rosal",
    		"Facatativa",
    		"Fomeque",
    		"Fosca",
    		"Funza",
    		"Fuquene",
    		"Fusagasuga",
    		"Gachala",
    		"Gachancipa",
    		"Gacheta",
    		"Gama",
    		"Girardot",
    		"Granada",
    		"Guacheta",
    		"Guaduas",
    		"Guasca",
    		"Guataqui",
    		"Guatavita",
    		"Guayabal de Siquima",
    		"Guayabetal",
    		"Gutierrez",
    		"Jerusalen",
    		"Junin",
    		"La Calera",
    		"La Mesa",
    		"La Palma",
    		"La Pena",
    		"La Vega",
    		"Lenguazaque",
    		"Macheta",
    		"Madrid",
    		"Manta",
    		"Medina",
    		"Mosquera",
    		"Narino",
    		"Nemocon",
    		"Nilo",
    		"Nimaima",
    		"Nocaima",
    		"Venecia (Ospina Perez)",
    		"Pacho",
    		"Paime",
    		"Pandi",
    		"Paratebueno",
    		"Pasca",
    		"Puerto Salgar",
    		"Puli",
    		"Quebradanegra",
    		"Quetame",
    		"Quipile",
    		"Rafael",
    		"Ricaurte",
    		"San Antonio de Tequendama",
    		"San Bernardo",
    		"San Cayetano",
    		"San Francisco",
    		"San Juan de Rioseco",
    		"Sasaima",
    		"Sesquile",
    		"Sibate",
    		"Silvania",
    		"Simijaca",
    		"Soacha",
    		"Sopo",
    		"Subachoque",
    		"Suesca",
    		"Supata",
    		"Susa",
    		"Sutatausa",
    		"Tabio",
    		"Tausa",
    		"Tena",
    		"Tenjo",
    		"Tibacuy",
    		"Tibirita",
    		"Tocaima",
    		"Tocancipa",
    		"Topaipi",
    		"Ubala",
    		"Ubaque",
    		"Ubate",
    		"Une",
    		"utica",
    		"Vergara",
    		"Viani",
    		"Villagomez",
    		"Villapinzon",
    		"Villeta",
    		"Viota",
    		"Yacopi",
    		"Zipacon",
    		"Zipaquira"
    	],
    	:"Choco" => [
    		"Acandi",
    		"Alto Baudo (Pie de Pato)",
    		"Atrato (Yuto)",
    		"Bagado",
    		"Bahia Solano (Mutis)",
    		"Bajo Baudo (Pizarro)",
    		"Bojaya (Bellavista)",
    		"Canton de San Pablo",
    		"Condoto",
    		"El Carmen",
    		"El Litoral de San Juan",
    		"Itsmina",
    		"Jurado",
    		"Lloro",
    		"Novita",
    		"Nuqui",
    		"Quibdo",
    		"Riosucio",
    		"San Jose del Palmar",
    		"Sipi",
    		"Tado",
    		"Unguia"
    	],
    	:"Guainia" => [
    		"Puerto Inirida"
    	],
    	:"Guaviare" => [
    		"Calamar",
    		"El Retorno",
    		"Miraflores",
    		"San Jose del Guaviare"
    	],
    	:"Huila" => [
    		"Acevedo",
    		"Agrado",
    		"Aipe",
    		"Algeciras",
    		"Altamira",
    		"Baraya",
    		"Campoalegre",
    		"Colombia",
    		"Elias",
    		"Garzon",
    		"Gigante",
    		"Guadalupe",
    		"Hobo",
    		"Iquira",
    		"Isnos",
    		"La Argentina",
    		"La Plata",
    		"Nataga",
    		"Neiva",
    		"Oporapa",
    		"Paicol",
    		"Palermo",
    		"Palestina",
    		"Pital",
    		"Pitalito",
    		"Rivera",
    		"Saladoblanco",
    		"San Agustin",
    		"Santa Maria",
    		"Suaza",
    		"Tarqui",
    		"Tesalia",
    		"Tello",
    		"Teruel",
    		"Timana",
    		"Villavieja",
    		"Yaguara"
    	],
    	:"La Guajira" => [
    		"Barrancas",
    		"Dibulla",
    		"Distraccion",
    		"El Molino",
    		"Fonseca",
    		"Hatonuevo",
    		"Maicao",
    		"Manaure",
    		"Riohacha",
    		"San Juan del Cesar",
    		"Uribia",
    		"Urumita",
    		"Villanueva"
    	],
    	:"Magdalena"=>[
    		"Aracataca",
    		"Ariguani (El Dificil)",
    		"Cerro San Antonio",
    		"Chivolo",
    		"Cienaga",
    		"El Banco",
    		"El Pinon",
    		"El Reten",
    		"Fundacion",
    		"Guamal",
    		"Pedraza",
    		"Pijino del Carmen",
    		"Pivijay",
    		"Plato",
    		"Publoviejo",
    		"Remolino",
    		"Salamina",
    		"San Sebastian de Buuenavista",
    		"San Zenon",
    		"Santa Ana",
    		"Santa Marta",
    		"Sitionuevo",
    		"Tenerife"
    	],
    	:"Meta" => [
    		"Acacias",
    		"Barranca de Upia",
    		"Cabuyaro",
    		"Castilla la Nueva",
    		"Cubarral",
    		"Cumaral",
    		"El Calvario",
    		"El Castillo",
    		"El Dorado",
    		"Fuente de Oro",
    		"Granada",
    		"Guamal",
    		"Mapiripan",
    		"Mesetas",
    		"La Macarena",
    		"La Uribe",
    		"Lejanias",
    		"Puerto Concordia",
    		"Puerto Gaitan",
    		"Puerto Lopez",
    		"Puerto Lleras",
    		"Puerto Rico",
    		"Restrepo",
    		"San Carlos de Guaroa",
    		"San Juan de Arama",
    		"San Juanito",
    		"San Martin",
    		"Villavicencio",
    		"Vistahermosa"
    	],
    	:"Narino" => [
    		"Alban (San Jose)",
    		"Aldana",
    		"Ancuya",
    		"Arboleda (Berruecos)",
    		"Barbacoas",
    		"Belen",
    		"Buesaco",
    		"Colon (Genova)",
    		"Consaca",
    		"Contadero",
    		"Cordoba",
    		"Cuaspud (Carlosama)",
    		"Cumbal",
    		"Cumbitara",
    		"Chachagui",
    		"El Charco",
    		"El Rosario",
    		"El Tablon",
    		"El Tambo",
    		"Francisco Pizarro",
    		"Funes",
    		"Guachucal",
    		"Guaitarilla",
    		"Gualmatan",
    		"Iles",
    		"Imues",
    		"Ipiales",
    		"La Cruz",
    		"La Florida",
    		"La Llanada",
    		"La Tola",
    		"La Union",
    		"Leiva",
    		"Linares",
    		"Los Andes (Sotomayor)",
    		"Magui (Payan)",
    		"Mallama (Piedrancha)",
    		"Mosquera",
    		"Olaya",
    		"Ospina",
    		"Pasto",
    		"Policarpa",
    		"Potosi",
    		"Providencia",
    		"Puerres",
    		"Pupiales",
    		"Ricaurte",
    		"Roberto Payan (San Jose)",
    		"Samaniego",
    		"Sandona",
    		"San Bernardo",
    		"San Lorenzo",
    		"San Pablo",
    		"San Pedro de Cartago",
    		"Santa Barbara (Iscuande)",
    		"Santa Cruz (Guachavez)",
    		"Sapuyes",
    		"Taminango",
    		"Tangua",
    		"Tumaco",
    		"Tuquerres",
    		"Yacuanquer"
    	],
    	:"Norte de Santander" => [
    		"Abrego",
    		"Arboledas",
    		"Bochalema",
    		"Bucarasica",
    		"Cacota",
    		"Cachira",
    		"Chinacota",
    		"Chitaga",
    		"Convencion",
    		"Cucuta",
    		"Cucutilla",
    		"Durania",
    		"El Carmen",
    		"El Tarra",
    		"El Zulia",
    		"Gramalote",
    		"Hacari",
    		"Herran",
    		"Labateca",
    		"La Esperanza",
    		"La Playa",
    		"Los Patios",
    		"Lourdes",
    		"Mutiscua",
    		"Ocana",
    		"Pamplona",
    		"Pamplonita",
    		"Puerto Santander",
    		"Ragonvalia",
    		"Salazar",
    		"San Calixto",
    		"San Cayetano",
    		"Santiago",
    		"Sardinata",
    		"Silos",
    		"Teorama",
    		"Tibu",
    		"Toledo",
    		"Villacaro",
    		"Villa del Rosario"
    	],
    	:"Putumayo" => [
    		"Colon",
    		"Mocoa",
    		"Orito",
    		"Puerto Asis",
    		"Puerto Caicedo",
    		"Puerto Guzman",
    		"Puerto Leguizamo",
    		"Sibundoy",
    		"San Francisco",
    		"San Miguel",
    		"Santiago",
    		"Villa Gamuez (La Hormiga)",
    		"Villa Garzon"
    	],
    	:"Quindio" => [
    		"Armenia",
    		"Buenavista",
    		"Calarca",
    		"Circasia",
    		"Cordoba",
    		"Filandia",
    		"Genova",
    		"La Tebaida",
    		"Montenegro",
    		"Pijao",
    		"Quimbaya",
    		"Salento"
    	],
    	:"Risaralda" => [
    		"Apia",
    		"Balboa",
    		"Belen de Umbria",
    		"Dos Quebradas",
    		"Guatica",
    		"La Celia",
    		"La Virginia",
    		"Marsella",
    		"Mistrato",
    		"Pereira",
    		"Pueblo Rico",
    		"Quinchia",
    		"Santa Rosa de Cabal",
    		"Santuario"
    	],
    	:"San Andres" => [
    		"Providencia",
    		"San Andres"
    	],
    	:"Santander" => [
    		"Aguada",
    		"Albania",
    		"Aratoca",
    		"Barbosa",
    		"Barichara",
    		"Barrancabermeja",
    		"Betulia",
    		"Bolivar",
    		"Bucaramanga",
    		"Cabrera",
    		"California",
    		"Capitanejo",
    		"Carcasi",
    		"Cepita",
    		"Cerrito",
    		"Charala",
    		"Charta",
    		"Chima",
    		"Chipata",
    		"Cimitarra",
    		"Concepcion",
    		"Confines",
    		"Contratacion",
    		"Coromoro",
    		"Curiti",
    		"El Carmen",
    		"El Guacamayo",
    		"El Penon",
    		"El Playon",
    		"Encino",
    		"Enciso",
    		"Florian",
    		"Floridablanca",
    		"Galan",
    		"Gambita",
    		"Giron",
    		"Guaca",
    		"Guadalupe",
    		"Guapota",
    		"Guavata",
    		"Guepsa",
    		"Hato",
    		"Jesus Maria",
    		"Jordan",
    		"La Belleza",
    		"Landazuri",
    		"La Paz",
    		"Lebrija",
    		"Los Santos",
    		"Macaravita",
    		"Malaga",
    		"Matanza",
    		"Mogotes",
    		"Molagavita",
    		"Ocamonte",
    		"Oiba",
    		"Onzaga",
    		"Palmar",
    		"Palmas del Socorro",
    		"Paramo",
    		"Pie de Cuesta",
    		"Pinchote",
    		"Puente Nacional",
    		"Puerto Parra",
    		"Puerto Wilches",
    		"Rionegro",
    		"Sabana de Torres",
    		"San Andres",
    		"San Benito",
    		"San Gil",
    		"San Joaquin",
    		"San Jose de Miranda",
    		"San Miguel",
    		"San Vicente de Chucuri",
    		"Santa Barbara",
    		"Santa Helena del Opon",
    		"Simacota",
    		"Socorro",
    		"Suaita",
    		"Sucre",
    		"Surata",
    		"Tona",
    		"Valle de San Jose",
    		"Velez",
    		"Vetas",
    		"Villanueva",
    		"Zapatoca"
    	],
    	:"Sucre" => [
    		"Buenavista",
    		"Caimito",
    		"Coloso (Ricaurte)",
    		"Corozal",
    		"Chalan",
    		"Galeras (Nueva Granada)",
    		"Guaranda",
    		"La Union",
    		"Los Palmitos",
    		"Majagual",
    		"Morroa",
    		"Ovejas",
    		"Palmito",
    		"Sampues",
    		"San Benito Abad",
    		"San Juan de Betulia",
    		"San Marcos",
    		"San Onofre",
    		"San Pedro",
    		"Since",
    		"Sincelejo",
    		"Sucre",
    		"Tolu",
    		"Toluviejo"
    	],
    	:"Tolima" => [
    		"Alpujarra",
    		"Alvarado",
    		"Ambalema",
    		"Anzoategui",
    		"Armero (Guayabal)",
    		"Ataco",
    		"Cajamarca",
    		"Carmen de Apicala",
    		"Casabianca",
    		"Chaparral",
    		"Coello",
    		"Coyaima",
    		"Cunday",
    		"Dolores",
    		"Espinal",
    		"Falan",
    		"Flandes",
    		"Fresno",
    		"Guamo",
    		"Herveo",
    		"Honda",
    		"Ibague",
    		"Icononzo",
    		"Lerida",
    		"Libano",
    		"Mariquita",
    		"Melgar",
    		"Murillo",
    		"Natagaima",
    		"Ortega",
    		"Palocabildo",
    		"Piedras",
    		"Planadas",
    		"Prado",
    		"Purificacion",
    		"Rioblanco",
    		"Roncesvalles",
    		"Rovira",
    		"Saldana",
    		"San Antonio",
    		"San Luis",
    		"Santa Isabel",
    		"Suarez",
    		"Valle de San Juan",
    		"Venadillo",
    		"Villahermosa",
    		"Villarrica"
    	],
    	:"Valle" => [
    		"Alcala",
    		"Andalucia",
    		"Ansermanuevo",
    		"Argelia",
    		"Bolivar",
    		"Buenaventura",
    		"Buga",
    		"Bugalagrande",
    		"Caicedonia",
    		"Cali",
    		"Calima (Darien)",
    		"Candelaria",
    		"Cartago",
    		"Dagua",
    		"El aguila",
    		"El Cairo",
    		"El Cerrito",
    		"El Dovio",
    		"Florida",
    		"Ginebra",
    		"Guacari",
    		"Jamundi",
    		"La Cumbre",
    		"La Union",
    		"La Victoria",
    		"Obando",
    		"Palmira",
    		"Pradera",
    		"Restrepo",
    		"Riofrio",
    		"Roldanillo",
    		"San Pedro",
    		"Sevilla",
    		"Toro",
    		"Trujillo",
    		"Tulua",
    		"Ulloa",
    		"Versalles",
    		"Vijes",
    		"Yotoco",
    		"Yumbo",
    		"Zarzal"
    	],
    	:"Vaupes" => [
    		"Caruru",
    		"Mitu",
    		"Tatama"
    	],
    	:"Vichada" => [
    		"La Primavera",
    		"Puerto Carreno",
    		"Santa Rosalia",
    		"Cumaribo"
    	]
    }
	end
	
end
